[package]
name = "rawget"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.9.1"
url = "2.5.4"
smoltcp = { version = "0.12.0", features = ["std", "proto-ipv4", "phy-tuntap_interface"] }
hickory-proto = "0.25.2"
